### ISSUE TITLE
Install new app

### ISSUE THREAD

**Issue by ambiprospect** [holochain/launcher-tauri#120]
I have succeeded to download the Launcher and found only one app: DevHub-0.0.162. When I open it I got a list of All hApps, but I don't succeed to download any of those. What's wrong?

**Comment by matthme** [comment]
Hi @ambiprospect ! There is a new launcher version coming out very soon (likely today or tomorrow). The version you installed uses an outdated holochain version.
The DevHub app you opened is the app for developers to upload their apps, that's not what you need. The UX could be a bit more straight forward there (and will be soon).
If you want to install an app you would need to click on the "install app" button in the bottom right corner of the main screen instead and wait until other peers gossip the apps over to you. But since it is an old version there may not be many peers at this point so I recommend to wait for the new release. I will ping you here when it's out.

**Comment by ambiprospect** [comment]
Thanks @matthme , that was what I suspected after I had listened to the AMA no. 52. I am perhaps too eager to find out Holochain in Action.

**Comment by matthme** [comment]
@ambiprospect a new release is out now finally: https://github.com/holochain/launcher/releases/tag/v0.8.0
It should at least have 2 apps in the App Library at the moment that you can test :).
I'll close this issue now but happy to get more feedback if you find other issues!
