### ISSUE TITLE
Regression: `we.webhapp` installs on Launcher 0.7.1 but not on 0.8.0

### ISSUE THREAD

**Issue by littlebenlittle** [holochain/launcher-tauri#127]
**Describe the bug**

Unable to install `we` on Launcher 0.8.0. Error message "Failed to resolve hApp bundle".

hApp installs OK on Launcher 0.7.1.

**To Reproduce**

1. Download [`we.webhapp`](https://github.com/lightningrodlabs/we/releases/tag/v0.0.9) v0.0.9
2. From Holochain Launcher, click install `+ Install New App`
3. Click `Select App from Filesystem`
4. Select `we.webhapp`

**Expected behavior**

happ should install

**Logs**

[launcher.log](https://github.com/holochain/launcher/files/10582264/launcher.log)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Holochain Launcher Version 0.8.0

**Comment by matthme** [comment]
Hi Ben, this is due to the Launcher 0.8.0 using a newer Holochain version which had a breaking change when in the app bundle format. Luckily with the next upcoming Launcher release, Holochain will be stable for quite a while and those kind of issues should not appear again. I'll close the issue because there's nothing I can do from a Launcher perspective.
