### ISSUE TITLE
Error Launching Holochain Launcher - 'Could not get currently installed apps'

### ISSUE THREAD

**Issue by AlchemicalSpiralizer** [holochain/launcher-tauri#136]
Opening Launcher leads to a message stating 'Error Launching Holochain' - 'Holochain Version 0.1.3 threw an exception: Other("Could not get the currently installed apps")'

I am running MacOs Ventura v13.1 on a M1 chipset.
Using Holochain Launcher v. 0.9

Logs are attached
Screen shot is attached

No Holochain or lair processes were running in the Activity Monitor prior to trying to start Launcher.

**Additional context**
[launcher.log](https://github.com/holochain/launcher/files/10798378/launcher.log)

<img width="1197" alt="Screenshot 2023-02-21 at 22 38 14" src="https://user-images.githubusercontent.com/102468659/220476217-249fc5d1-b07b-4e0f-9085-334308570c16.png">

**Comment by matthme** [comment]
Thank you for the bug report! I had a quick look into your logs and I can see that it's the same issue as #65. You can see in [this](https://github.com/holochain/launcher/issues/65#issuecomment-1248126594) comment how you can workaround it if it turns out to appear regularly.
Unfortunately I cannot do much on the Launcher side but hopefully at some point Holochain core can deal with this scenario.

**Comment by AlchemicalSpiralizer** [comment]
Hi Matt,

Thanks for letting me know and pointing me towards a solution! Would you
like me to mark the bug as “close as completed” or “ close as not planned”?

All the best,

Sam

**Comment by matthme** [comment]
Good question :). I would say it can be considered a duplicate so neither of them really fits. I'll just close it as "not planned" if that's okay. Thank you!
