### ISSUE TITLE
Searching for peers

### ISSUE THREAD

**Issue by beddows** [holochain/launcher-tauri#221]
First time using Holochain. The App Store seems stuck on "Searching for peers...".

I installed on MacOS: Holochain Launcher vO.11.5 (Beta 0.2), Holochain v0.2.6, Lair Keystore vO.4.2. Tried restarting launcher and reinstalling.

[launcher.log](https://github.com/holochain/launcher/files/14961952/launcher.log) shows "error 508: Cannot create socket" and subsequent timeouts.

**Comment by matthme** [comment]
Hi @beddows thanks for raising the issue. I'm sorry to hear that your first interaction with Holochain does not seem to be the best. We are currently working on a larger refactor of the Holochain Launcher of which the first version hopefully gets released quite soon.
It's therefore possible that there are currently very few people actively using the Launcher and there may simply be no-one online (I just started mine up in case you're still online so that you might start seeing something in the App Store). In the meantime, if you just want to try out Holochain I can recommend you to give a look at https://theweave.social/moss/ which is an alternative launcher for holochain apps targeted at groups and which is currently quite actively used so you should have less trouble finding other peers. You can find an invitation link to a public group in [this](https://happeningscommunity.substack.com/p/we-is-now-the-weave?r=e6jau&utm_campaign=post&utm_medium=web&triedRedirect=true) blog post.

**Comment by beddows** [comment]
Thanks for the quick reply @matthme. I just figured it out - I had Cloudflare Warp running and it's not compatible with Holochain. Thanks for the Moss link, will take a look!
