### ISSUE TITLE
Holochain Launcher Setup Wizard ended prematurely 

### ISSUE THREAD

**Issue by strzelbka** [holochain/launcher-tauri#32]
"There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact support,,,"

**Comment by strzelbka** [comment]
issue nr 32....it's more like issue nr 32000, only i cared to opened account here and post it. Come on Holo, I spent week reading, watching videos, listening to people, just to have "cant install app" experience....

**Comment by guillemcordoba** [comment]
Hi @strzelbka ! Thanks for going through the effort of creating an account and posting an issue.

Firstly, the Launcher is still in alpha and is not production ready, so there will be bugs. The purpose of this pre-release is to start to gather feedback just like this one (so thanks!). It's totally fine if you want to wait until a more production-ready release is out :) 

What I think we can do is make that clearer in the releases page, to adjust the expectations of the users.

About your issue... We are using Tauri to package our Launcher, so the problem you are seeing is not really a problem of the Launcher per se but of Tauri. Let's see if we can debug it to help the Tauri developers fix it:

1. Can you check that the problem was not that your PC was offline when you tried to install the Holochain Launcher?
  - See [this issue](https://github.com/tauri-apps/tauri/discussions/2242).
2. If you are online, and try installing again, and the issue persists, could you try installing the [`WebView` package](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) and retrying again?

Let me know how it goes!

**Comment by strzelbka** [comment]
i have installed webview package, and this time there was no issue, i did install it.

Many thanks!
