### ISSUE TITLE
Cannot install hApps (Launcher v.0.4.4 and DevHub)

### ISSUE THREAD

**Issue by its0din-ai** [holochain/launcher-tauri#48]
**Describe the bug**
Users can't install hApps, from hApps Library and/or from the DevHub pages

**To Reproduce**
1. Go to DevHub
2. Click on "hApps section on the Left Sidebar"
3. Choose hApps, in this case is Notebooks
4. Click on More info on the Right Side
5. In the Releases Section, below the pages. choose hApps release version, and click More Info
6. On the Bottom Right, there's a Download Button
7. Click it, and See the Error

**Expected behavior**
The Users should be able to download hApps and Install it locally

**Logs**
[launcher.log](https://github.com/holochain/launcher/files/8688673/launcher.log)

**Screenshots**
![Launcher-bug](https://user-images.githubusercontent.com/81013584/168307364-4820eda6-2d8b-430b-921e-0b989ceeca02.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro ver. 21H2
 - Holochain Launcher Version 0.4.4

**Comment by guillemcordoba** [comment]
Thanks for the feedback :D

This is because gossip takes a bit of time to propagate all the files in the DHT... If you retry it after some minutes it should work.

This is actually a problem in the current design of the DevHub happ, where all the files live in the same big DHT. I think this will be chaned in a future version for the DevHub, stay tuned to this repo: https://github.com/holochain/devhub-dnas.
