### ISSUE TITLE
Launcher V0.71 deb packege fails to install properly

### ISSUE THREAD

**Issue by lucode** [holochain/launcher-tauri#92]
**Describe the bug**
On my Ubuntu System I had a previous version of Launcher installed. The first attempt to upgrade seems to work, but I couldn't download any hApps from the store. Then I did a Factory reset, an uninstall and a purge, but somehow my old profile was persistent.
And after a new install I got an error, which disappeared after an another Factory reset.  
BIG QUESTION where are the other profile data stored incl. my password?  

**To Reproduce**
1. I tried again uninstalled and deleted manually all Holochain related folders in my Home dir, but my previous credentials where still present, including the bug.  
2. I did execute the steps from + again but this time I installed / run the appimage. Result was the same.

**Expected behavior**

**Logs**
[launcher.log](https://github.com/holochain/launcher/files/9972015/launcher.log)

**Error when I try to download a package from Dev-Hub**
ErrorPayload
[UserError::EntryNotFoundError( Record not found for Entry address 'uhCEk3ZbEUxwVP6FwEJl0l6Cfi-LD5yRggH2JguOzCj17l5eTHl6F': )]

**Screenshots**
![image](https://user-images.githubusercontent.com/2928740/200864639-46cd03c6-a02e-47ab-a1ba-4780410f7ebd.png)

**Desktop (please complete the following information):**
 - OS: [Feren OS (Ubuntu 20.4)]
 - Holochain Launcher Version [V0.71]
 
**Additional context**

**Comment by matthme** [comment]
If I understand correctly, you describe more than one issue:

1. not being able to download hApps from the App Library. This is likely issue #64 and it is being worked on on the Holochain side. A factory reset will not help here but what usually works is letting the launcher run for a while so that it has time to synchronize all the files with its peers.
2. Your old "profile" still being present after a factory reset. I need further information to understand this. What do you mean by "profile" exactly? What is it that remains? A factory reset should prompt you to create a new password and is supposed to delete the apps installed, the keystore where your private keys were stored and any configuration files.

**Comment by lucode** [comment]
Ok, it seems that ev. I was dragged into false assumptions here. About point 2.  indeed it did puzzle me that Factory Reset didn't change anything in my case (as well as deleting config files manually). After a restart I got directly to the login page, which then opened the app with the old password. It seems really that there are several issues here.   
Profil data is probably a puzzling term, because in the case of the Launcher it is only the credentials and keys.

Ok I waited several minutes with the open App Library and then installing did work fine. Would help to place a note there in the UI that loading in the background of all the files is required first. Or even better to disable the Install buttons until everything is fine.

**Comment by matthme** [comment]
Okay glad it worked after waiting a while. That's right, the UI regarding this should be improved (and probably will be by the next release).

Regarding point 2, I have never encountered that a factory reset did not prompt for creating a new password (the "create new password" page does look almost the same as the normal login page thought except that it asks you to repeat the password). In case this should happen again, let us know please. I cannot infer anything about it from your log files unfortunately because they seem not to contain the logs before the factory reset (which I assume is because you deleted the log file manually, the log file is supposed to persist across factory resets otherwise).

**Comment by matthme** [comment]
There's a new release out now that should have better UX around the App Library synchronization process and should also be faster in synchronization in general due to underliyng gossip improvments in holochain: https://github.com/holochain/launcher/releases/tag/v0.8.0

I'll close this now but in case some of the reported issues turn up again, feel free to reopen it.
