### ISSUE TITLE
Holochain Launcher not working, sometimes yes, mostly not. No hApps

### ISSUE THREAD

**Issue by uwenohg** [holochain/launcher-tauri#98]
**Describe the bug**
Starting the app gives me this error:
Holochain Version 0.0.162 threw an exception: LaunchHolochainError(CouldNotInitializeConductor(UnknownError("Unknown error when trying to initialize conductor. See log file for details.")))
When resetting to factory default, tha app starts and works but shows no happs to install...

**To Reproduce**
1. Reset the Launcher to factrory
First time it starts, but no happs to install
second time starting breaks, see image.

![holochain launcher](https://user-images.githubusercontent.com/45289075/204107992-81c808f6-5afa-48c2-8983-767cddfc9b73.jpg)

**Expected behavior**
Would like to see and install happs like we or others...
"There are no apps available yet in the DevHub.
Read this to learn how to publish a Holochain application to the DevHub."

**Logs**
Please attach here the `launcher.log` file. To find it, go to `Holochain Admin` window of the Holochain Launcher, select the  `Settings` menu, and select `Open Logs`. Attach that file to this issue.

see no way to upload logfile. (?)

> In Ubuntu, there is a weird error that prevents the upload of a file from inside a hidden folder. To work around it, you can copy the `launcher.log` file to another non-hidden location, and upload it from there.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs v.13.0.1]
 - Holochain Launcher Version [e.g. 0.], you can find out in `Help` > 'About'
 - 0.7.1

**Additional context**

**Comment by matthme** [comment]
Hello Uwe. I'm sorry for the troubles you have with the launcher. The `LaunchHolochainError` is most likely related to #82 . It's probably one or more orphan holochain process(es) still running in the background, for example because you have force quit the launcher earlier. With the next launcher release there will be a more helpful error message. To fix it, quit the launcher and look for remaining processes that start with `holochain-v` and kill them. After that the launcher should start up fine again.
Then the second issue you mention about no happs being visible in the app library is probably due to #64 . The launcher will need a while to synchronize the data with other peers so if you wait a while apps should start appearing. This will be improved in the future.

**Comment by matthme** [comment]
I'm closing this issue since there has been a new Launcher release in the meantime that addressed those issues.
